# Generated by Django 3.2.3 on 2021-05-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, verbose_name='email')),
                ('name', models.CharField(max_length=30, verbose_name='user name')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='registerd date')),
                ('level', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=8, verbose_name='level')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'Shoppingmall_users',
            },
        ),
    ]
