# Generated by Django 3.2.3 on 2021-05-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='mobile number'),
        ),
    ]
