# Generated by Django 3.2.3 on 2021-05-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210526_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=128, unique=True, verbose_name='email'),
        ),
    ]
