# Generated by Django 3.2.3 on 2021-06-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210528_0103'),
        ('product', '0002_auto_20210531_1423'),
    ]

    operations = [
    ]
