# Generated by Django 3.2 on 2021-05-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Info',
            fields=[
                ('device_serial', models.IntegerField(primary_key=True, serialize=False)),
                ('device_model', models.CharField(default='', max_length=15)),
                ('device_name', models.CharField(default='', max_length=15)),
                ('device_detail', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Info',
            fields=[
                ('farm_type', models.CharField(max_length=15)),
                ('farm_name', models.CharField(default='', max_length=20)),
                ('farm_capacity', models.IntegerField(default=1)),
                ('farm_no', models.IntegerField(primary_key=True, serialize=False)),
                ('device_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_management.device_info')),
            ],
        ),
    ]
