# Generated by Django 3.2 on 2021-05-26 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_group', models.IntegerField()),
                ('crop_name', models.CharField(max_length=20)),
                ('life_stage', models.IntegerField()),
                ('planting_date', models.DateField()),
                ('farm_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_management.farm_info')),
            ],
        ),
        migrations.CreateModel(
            name='Growth_Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('germination_time', models.IntegerField()),
                ('seeding_ec', models.FloatField()),
                ('ec', models.FloatField()),
                ('progress_date', models.IntegerField()),
                ('temparature', models.IntegerField()),
                ('ph', models.FloatField()),
                ('humidity', models.FloatField()),
                ('date', models.DateField()),
                ('light_hr', models.IntegerField()),
                ('device_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_management.device_info')),
                ('plant_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_management.plant_info')),
            ],
        ),
    ]
