# Generated by Django 3.2.3 on 2021-06-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_info',
            name='farm_name',
            field=models.CharField(default='farm2021-06-03-11:42:05-PM', max_length=30),
        ),
        migrations.AlterField(
            model_name='plant_info',
            name='planting_date',
            field=models.DateField(),
        ),
    ]
