# Generated by Django 3.2.3 on 2021-06-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm_info',
            name='farm_no',
        ),
        migrations.AddField(
            model_name='farm_info',
            name='farm_model_no',
            field=models.CharField(default='Smart farm 20', max_length=15),
        ),
        migrations.AddField(
            model_name='farm_info',
            name='farm_plant_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farm_info',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, unique=True, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm_info',
            name='farm_name',
            field=models.CharField(default='farm2021-06-04-06:24:06-PM', max_length=30),
        ),
        migrations.AlterField(
            model_name='plant_info',
            name='crop_group',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='plant_info',
            name='life_stage',
            field=models.CharField(max_length=15),
        ),
    ]
