# Generated by Django 3.2 on 2021-05-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0002_growth_params_plant_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info',
            name='deivce_password',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='device_info',
            name='device_ip_address',
            field=models.CharField(default='0.0.0.0', max_length=40),
        ),
        migrations.AlterField(
            model_name='plant_info',
            name='crop_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
