# Generated by Django 3.2.3 on 2021-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0002_auto_20210604_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_info',
            name='farm_name',
            field=models.CharField(default='farm2021-06-04-11:24:21-PM', max_length=30),
        ),
    ]
