# Generated by Django 3.2.3 on 2021-05-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0005_mock_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_info',
            name='crop_group',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='plant_info',
            name='life_stage',
            field=models.CharField(max_length=15),
        ),
    ]
