# Generated by Django 3.2.3 on 2021-05-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0006_auto_20210530_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm_info',
            name='farm_no',
        ),
        migrations.RemoveField(
            model_name='plant_info',
            name='farm_info',
        ),
        migrations.AddField(
            model_name='farm_info',
            name='farm_model_no',
            field=models.CharField(default='Smart farm 20', max_length=15),
        ),
        migrations.AddField(
            model_name='farm_info',
            name='farm_plant_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farm_info',
            name='id',
            field=models.AutoField(auto_created=True, default=int, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant_info',
            name='planting_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
